/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Chart: typeof import('./components/Chart.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiAccountMenu: typeof import('./components/ui/account-menu.vue')['default']
    UiNavBar: typeof import('./components/ui/nav-bar.vue')['default']
    UiTopBar: typeof import('./components/ui/top-bar.vue')['default']
  }
}
